sudo: false
language: php

php:
  - 5.5
  - 5.6

env:
  - RUNPORT=8080

services:
  - mysql

git:
  submodules: false

addons:
  apt:
    packages:
    - php5-cgi
    - php5-fpm
    - php5-mysql
    - php5-curl
    - php5-gd
    - net-tools

before_install:
  - git submodule init
  - git submodule update
  - |
    echo -e "[mysqld]
    innodb_large_prefix = true
    innodb_file_format_max = barracuda" | sudo tee /etc/mysql/conf.d/travis.cnf
  - sudo /etc/init.d/mysql restart

install:
  - mysql -e 'create database neticrmci CHARACTER SET utf8 COLLATE utf8_general_ci'
  - mysql -uneticrmci -e 'SHOW VARIABLES LIKE "innodb_file_format_max"'

before_script:

script:
  - ls
  - sh run.sh

notifications:
  email:
    recipients:
      - junsuwhy@netivism.com.tw
    on_success: always
    on_failure: always

after_failure: